const actionTypes ={
    bookActions:{
        GET_BOOKS_START:"GET_BOOKS_START",
        GET_BOOKS_SUCCESS:"GET_BOOKS_SUCCESS",
        GET_BOOKS_FAİL:"GET_BOOKS_FAİL",
        ADD_BOOK:"ADD_BOOK",
        DELETE_BOOK:"DELETE_BOOK",
        EDIT_BOOK:"EDIT_BOOK",
        DELETE_BOOKS_AFTER_DELETE_CATEGORY:"DELETE_BOOKS_AFTER_DELETE_CATEGORY"
    },
    categoryAction:{
        GET_CATEGORY_START:"GET_CATEGORY_START",
        GET_CATEGORY_SUCCESS:"GET_CATEGORY_SUCCESS",
        GET_CATEGORY_FAİL:"GET_CATEGORY_FAİL",
        ADD_CATEGORIES:"ADD_CATEGORIES" ,
        DELETE_CATEGORIES:"DELETE_CATEGORIES",
        EDIT_CATEGORIES:"EDIT_CATEGORIES"
    }
}

export default actionTypes